napcat:
  config:
    # 这是napcat发起请求的基础路径
    base_url: http://192.168.31.100:3000
    # 这是监听websocket的基础路径
    base_ws_url: ws://192.168.31.100:5788/
    # 这是napcat的管理员QQ号
    admin_id: 2030236097
    # 这是管理员的qq姓名
    admin_name: Wang
    # 这是向napcat发起请求的超时时间
    timeout: 60

  qq_api:
    base_private_api:
    #基本私聊api
      {
        "user_id": "",
        "message": []
      }
    base_group_api:
    #基本群聊api
      {
        "group_id": "",
        "message": []
      }
    base_path:
      private: "/send_private_msg"
      group: "/send_group_msg"
      禁言: "/set_group_ban"
      群公告: "/_send_group_notice"


